### PR TITLE
Add first cut of orderly diagrams

### PR DESCRIPTION
**Pull request by r-ash**
Still todo
* Make diagrams look nice
* Add detail to orderlyweb parts
* Add some markdown doc with it with more documentation incl notes about current deployments 
* orderly.rstudio? - maybe just a comment in the markdown
* orderly.sharepoint?

Created using https://app.diagrams.net/ you can load the .drawio file and edit

### CODE REVIEW

**Review by mwoodbri — COMMENTED** [review]
This is already very helpful.

Only question I have is whether this is intended to document the VIMC setup (as the canonical deployment of orderly and supporting projects) or be a more abstract representation of the orderly ecosystem and dependencies between them (for potential adopters).

If the former then I guess it needs to include Montagu (webapps, DB, API, proxy, task queue, Python client etc).

If latter (i.e. for a broader audience) then it could definitely do with something explaining the purpose of each component, and which (if any) are optional. But I know that's on the to-do list!

**Review by EmmaLRussell — COMMENTED** [review]
This is going to be really useful!

As Mark says, would be good to clarify if this is to be a montagu-specific diagram. If not, should maybe replace the 'montagu-' references with something more generic? Could have a montagu version too alongside the existing montagu architecture diagrams (which probably need updating!) and which are here: https://github.com/vimc/montagu-machine/tree/master/docs/diagrams

Orderly-web has so far avoided dealing with the file system on the orderly volume, and just communicates with the db, so I guess that arrow could point directly to the db rather than the whole volume. Though that state of affairs may change! 

Is there more detail to be shown inside orderly.server worker? Should that have Orderly inside it, as the R client does?

**Comment by mwoodbri** [comment]
> Orderly-web has so far avoided dealing with the file system on the orderly volume, and just communicates with the db, so I guess that arrow could point directly to the db rather than the whole volume. Though that state of affairs may change!

I might have misunderstood, but doesn't OW retrieve report artefacts directly from the filesystem?

**Comment by EmmaLRussell** [comment]
> > Orderly-web has so far avoided dealing with the file system on the orderly volume, and just communicates with the db, so I guess that arrow could point directly to the db rather than the whole volume. Though that state of affairs may change!
> 
> I might have misunderstood, but doesn't OW retrieve report artefacts directly from the filesystem?

Yes, of course, you're right. Sorry, ignore me.

**Review by richfitz — CHANGES_REQUESTED** [review]
Suggest:
* Don't worry about prettification, that can be done later
* This would be best as a non-montagu specific diagram
* A few notes about arrows (e.g., if you do two arrows showing how OW interacts with the filesystem) would be great

**Comment by r-ash** [comment]
Thanks all, I've removed any `montagu` specific stuff so diagram should be only orderly and added a md document containing a brief overview of each of the components with some links. Also added notes into that document about project specific configuration which hopefully should cover the removed `montagu` specific bits from the diagram.

**Review by mwoodbri — APPROVED** [review]

**Review by richfitz — APPROVED** [review]

**Pull request merged**
